# Site settings
title:  
email: brycelelbach@gmail.com 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://brycelelbach.github.io" # the base hostname & protocol for your site
github_username:  brycelelbach
twitter_username: blelbach

# Build settings
markdown: kramdown
#highlighter: rouge
kramdown:
  input: GFM
